// ─── NSE Stocks by Sector ─────────────────────────────────────────────────────
export const SECTORS = {
  'Banking & Finance': [
    { label: 'HDFC Bank',        sym: 'HDFCBANK.NS' },
    { label: 'ICICI Bank',       sym: 'ICICIBANK.NS' },
    { label: 'SBI',              sym: 'SBIN.NS' },
    { label: 'Kotak Bank',       sym: 'KOTAKBANK.NS' },
    { label: 'Axis Bank',        sym: 'AXISBANK.NS' },
    { label: 'Bajaj Finance',    sym: 'BAJFINANCE.NS' },
    { label: 'Bajaj Finserv',    sym: 'BAJAJFINSV.NS' },
    { label: 'IndusInd Bank',    sym: 'INDUSINDBK.NS' },
    { label: 'Bandhan Bank',     sym: 'BANDHANBNK.NS' },
    { label: 'Federal Bank',     sym: 'FEDERALBNK.NS' },
    { label: 'PNB',              sym: 'PNB.NS' },
    { label: 'Bank of Baroda',   sym: 'BANKBARODA.NS' },
    { label: 'Canara Bank',      sym: 'CANBK.NS' },
    { label: 'IDFC First Bank',  sym: 'IDFCFIRSTB.NS' },
    { label: 'RBL Bank',         sym: 'RBLBANK.NS' },
  ],
  'IT & Technology': [
    { label: 'TCS',              sym: 'TCS.NS' },
    { label: 'Infosys',          sym: 'INFY.NS' },
    { label: 'Wipro',            sym: 'WIPRO.NS' },
    { label: 'HCL Tech',         sym: 'HCLTECH.NS' },
    { label: 'Tech Mahindra',    sym: 'TECHM.NS' },
    { label: 'LTIMindtree',      sym: 'LTIM.NS' },
    { label: 'Mphasis',          sym: 'MPHASIS.NS' },
    { label: 'Coforge',          sym: 'COFORGE.NS' },
    { label: 'Persistent',       sym: 'PERSISTENT.NS' },
    { label: 'OFSS',             sym: 'OFSS.NS' },
    { label: 'Hexaware',         sym: 'HEXAWARE.NS' },
    { label: 'Cyient',           sym: 'CYIENT.NS' },
  ],
  'Oil & Gas': [
    { label: 'Reliance',         sym: 'RELIANCE.NS' },
    { label: 'ONGC',             sym: 'ONGC.NS' },
    { label: 'IOC',              sym: 'IOC.NS' },
    { label: 'BPCL',             sym: 'BPCL.NS' },
    { label: 'HPCL',             sym: 'HINDPETRO.NS' },
    { label: 'GAIL',             sym: 'GAIL.NS' },
    { label: 'IGL',              sym: 'IGL.NS' },
    { label: 'MGL',              sym: 'MGL.NS' },
    { label: 'Gujarat Gas',      sym: 'GUJGASLTD.NS' },
  ],
  'Auto & EV': [
    { label: 'Maruti Suzuki',    sym: 'MARUTI.NS' },
    { label: 'Tata Motors',      sym: 'TATAMOTORS.NS' },
    { label: 'M&M',              sym: 'M&M.NS' },
    { label: 'Bajaj Auto',       sym: 'BAJAJ-AUTO.NS' },
    { label: 'Hero MotoCorp',    sym: 'HEROMOTOCO.NS' },
    { label: 'Eicher Motors',    sym: 'EICHERMOT.NS' },
    { label: 'TVS Motor',        sym: 'TVSMOTOR.NS' },
    { label: 'Ashok Leyland',    sym: 'ASHOKLEY.NS' },
    { label: 'Bosch',            sym: 'BOSCHLTD.NS' },
    { label: 'Motherson Sumi',   sym: 'MOTHERSON.NS' },
  ],
  'FMCG': [
    { label: 'HUL',              sym: 'HINDUNILVR.NS' },
    { label: 'ITC',              sym: 'ITC.NS' },
    { label: 'Nestle India',     sym: 'NESTLEIND.NS' },
    { label: 'Britannia',        sym: 'BRITANNIA.NS' },
    { label: 'Dabur',            sym: 'DABUR.NS' },
    { label: 'Marico',           sym: 'MARICO.NS' },
    { label: 'Godrej Consumer',  sym: 'GODREJCP.NS' },
    { label: 'Colgate',          sym: 'COLPAL.NS' },
    { label: 'Emami',            sym: 'EMAMILTD.NS' },
    { label: 'Varun Beverages',  sym: 'VBL.NS' },
  ],
  'Pharma & Healthcare': [
    { label: 'Sun Pharma',       sym: 'SUNPHARMA.NS' },
    { label: 'Dr Reddy\'s',      sym: 'DRREDDY.NS' },
    { label: 'Cipla',            sym: 'CIPLA.NS' },
    { label: 'Divi\'s Labs',     sym: 'DIVISLAB.NS' },
    { label: 'Apollo Hospitals', sym: 'APOLLOHOSP.NS' },
    { label: 'Lupin',            sym: 'LUPIN.NS' },
    { label: 'Torrent Pharma',   sym: 'TORNTPHARM.NS' },
    { label: 'Biocon',           sym: 'BIOCON.NS' },
    { label: 'Aurobindo Pharma', sym: 'AUROPHARMA.NS' },
    { label: 'Max Healthcare',   sym: 'MAXHEALTH.NS' },
  ],
  'Metals & Mining': [
    { label: 'Tata Steel',       sym: 'TATASTEEL.NS' },
    { label: 'Hindalco',         sym: 'HINDALCO.NS' },
    { label: 'JSW Steel',        sym: 'JSWSTEEL.NS' },
    { label: 'Vedanta',          sym: 'VEDL.NS' },
    { label: 'Coal India',       sym: 'COALINDIA.NS' },
    { label: 'NMDC',             sym: 'NMDC.NS' },
    { label: 'SAIL',             sym: 'SAIL.NS' },
    { label: 'NALCO',            sym: 'NATIONALUM.NS' },
    { label: 'APL Apollo',       sym: 'APLAPOLLO.NS' },
  ],
  'Infra & Cement': [
    { label: 'L&T',              sym: 'LT.NS' },
    { label: 'UltraTech Cement', sym: 'ULTRACEMCO.NS' },
    { label: 'Grasim',           sym: 'GRASIM.NS' },
    { label: 'Ambuja Cements',   sym: 'AMBUJACEM.NS' },
    { label: 'ACC',              sym: 'ACC.NS' },
    { label: 'Adani Ports',      sym: 'ADANIPORTS.NS' },
    { label: 'Adani Enterprises',sym: 'ADANIENT.NS' },
    { label: 'DLF',              sym: 'DLF.NS' },
    { label: 'Oberoi Realty',    sym: 'OBEROIRLTY.NS' },
  ],
  'Power & Utilities': [
    { label: 'NTPC',             sym: 'NTPC.NS' },
    { label: 'Power Grid',       sym: 'POWERGRID.NS' },
    { label: 'Tata Power',       sym: 'TATAPOWER.NS' },
    { label: 'Adani Power',      sym: 'ADANIPOWER.NS' },
    { label: 'Adani Green',      sym: 'ADANIGREEN.NS' },
    { label: 'Torrent Power',    sym: 'TORNTPOWER.NS' },
    { label: 'CESC',             sym: 'CESC.NS' },
    { label: 'NHPC',             sym: 'NHPC.NS' },
  ],
  'Consumer & Retail': [
    { label: 'Asian Paints',     sym: 'ASIANPAINT.NS' },
    { label: 'Titan',            sym: 'TITAN.NS' },
    { label: 'Avenue Supermarts',sym: 'DMART.NS' },
    { label: 'Trent',            sym: 'TRENT.NS' },
    { label: 'Zomato',           sym: 'ZOMATO.NS' },
    { label: 'Nykaa',            sym: 'NYKAA.NS' },
    { label: 'Pidilite',         sym: 'PIDILITIND.NS' },
    { label: 'Havells',          sym: 'HAVELLS.NS' },
    { label: 'Voltas',           sym: 'VOLTAS.NS' },
  ],
};

export const NIFTY_INDICES = [
  {
    label: 'NIFTY 50',
    symbols: ['RELIANCE.NS','TCS.NS','HDFCBANK.NS','INFY.NS','ICICIBANK.NS',
              'HINDUNILVR.NS','ITC.NS','SBIN.NS','BHARTIARTL.NS','KOTAKBANK.NS',
              'LT.NS','BAJFINANCE.NS','HCLTECH.NS','WIPRO.NS','MARUTI.NS',
              'AXISBANK.NS','ASIANPAINT.NS','TITAN.NS','NTPC.NS','POWERGRID.NS'],
  },
  {
    label: 'NIFTY BANK',
    symbols: ['HDFCBANK.NS','ICICIBANK.NS','KOTAKBANK.NS','AXISBANK.NS',
              'SBIN.NS','INDUSINDBK.NS','BANDHANBNK.NS','FEDERALBNK.NS','PNB.NS','BANKBARODA.NS'],
  },
  {
    label: 'NIFTY IT',
    symbols: ['TCS.NS','INFY.NS','HCLTECH.NS','WIPRO.NS','TECHM.NS',
              'LTIM.NS','MPHASIS.NS','COFORGE.NS','PERSISTENT.NS','OFSS.NS'],
  },
  {
    label: 'NIFTY FMCG',
    symbols: ['HINDUNILVR.NS','ITC.NS','NESTLEIND.NS','BRITANNIA.NS',
              'DABUR.NS','MARICO.NS','GODREJCP.NS','COLPAL.NS','VBL.NS'],
  },
  {
    label: 'NIFTY AUTO',
    symbols: ['MARUTI.NS','TATAMOTORS.NS','M&M.NS','BAJAJ-AUTO.NS',
              'HEROMOTOCO.NS','EICHERMOT.NS','TVSMOTOR.NS','ASHOKLEY.NS'],
  },
  {
    label: 'NIFTY PHARMA',
    symbols: ['SUNPHARMA.NS','DRREDDY.NS','CIPLA.NS','DIVISLAB.NS',
              'LUPIN.NS','TORNTPHARM.NS','BIOCON.NS','AUROPHARMA.NS'],
  },
  {
    label: 'NIFTY METAL',
    symbols: ['TATASTEEL.NS','HINDALCO.NS','JSWSTEEL.NS','VEDL.NS',
              'COALINDIA.NS','NMDC.NS','SAIL.NS'],
  },
];
